import type{Metadata}from'next';import Link from'next/link';import{notFound}from'next/navigation';
const pages:Record<string,{title:string;kicker:string;intro:string;sections:{title:string;body:string}[]}>= {
 delivery:{title:'Pan-India Door-to-Door Delivery',kicker:'From Jaipur to your business',intro:'Packaging material is dispatched in protective master cartons to serviceable business PIN codes across India.',sections:[{title:'Share the destination',body:'Your PIN code, unloading constraints and delivery timeline help us choose the right road, courier or freight option.'},{title:'Protected for transit',body:'Finished packaging is bundled, master-packed and labelled to reduce crushing, moisture and handling damage.'},{title:'Clear landed estimate',body:'Manufacturing is quoted ex-GST. Freight is calculated separately so you can see the true delivered cost.'}]},
 sustainability:{title:'Practical Material Choices',kicker:'Lower impact, fit for purpose',intro:'We help businesses reduce unnecessary material while protecting the product and meeting real supply-chain conditions.',sections:[{title:'Right-size first',body:'Smaller dielines reduce board use, void fill and shipping volume.'},{title:'Paper-led structures',body:'Where appropriate, we prefer recyclable mono-material papers and clearly explain coatings or barriers.'},{title:'Repeatable sourcing',body:'Stable specifications make future runs consistent and easier to improve over time.'}]},
 samples:{title:'Samples & Prototyping',kicker:'Check before the bulk run',intro:'Structural samples and printed proofs are available for suitable custom projects before full production.',sections:[{title:'Stock sample',body:'Review an existing comparable construction and material.'},{title:'Plain prototype',body:'Confirm dimensions, fit, locking and load without printed artwork.'},{title:'Production proof',body:'For qualifying runs, check artwork position, colors and finishing expectations.'}]},
 help:{title:'Wholesale Help Centre',kicker:'Prepare a faster brief',intro:'The best quote starts with dimensions, packed product weight, quantity, material preference, printing and delivery PIN code.',sections:[{title:'Artwork',body:'Vector PDF, AI or CDR files with outlined fonts and linked images are preferred.'},{title:'Measurements',body:'Use internal length × width × depth in millimetres unless the product page specifies otherwise.'},{title:'Pricing',body:'Website bands are indicative. Final rates vary by board market, print coverage, finishing, volume and freight.'}]},
 contact:{title:'Contact Our Jaipur Studio',kicker:'Paper & Press',intro:'Send your bulk packaging requirement and our team will help define the most practical route to production.',sections:[{title:'Wholesale enquiries',body:'hello@paperandpress.com'},{title:'Working hours',body:'Monday–Saturday, 9:30–18:30 IST'},{title:'Service area',body:'Jaipur-based production coordination with door-to-door supply across serviceable Indian PIN codes.'}]},
 wholesale:{title:'Wholesale Supply Program',kicker:'For recurring requirements',intro:'Planned production for businesses, institutions, agencies and distributors buying packaging repeatedly.',sections:[{title:'Volume tiers',body:'Consolidate requirements or commit to repeat runs to improve manufacturing economics.'},{title:'Specification control',body:'Approved sizes, board grades and artwork are recorded for consistent reorders.'},{title:'Scheduled dispatch',body:'Split production and planned deliveries can support storage and cash-flow constraints.'}]},
 privacy:{title:'Privacy',kicker:'Your business information',intro:'Quote information is used only to understand, price and service your packaging enquiry.',sections:[{title:'What we collect',body:'Contact details, company information, product specifications, artwork and delivery data that you submit.'},{title:'How it is used',body:'To prepare quotes, coordinate samples, production and delivery, and support repeat orders.'}]},
 terms:{title:'Wholesale Terms',kicker:'Clear production expectations',intro:'Final commercial terms are provided with every written quotation and production approval.',sections:[{title:'Indicative prices',body:'Website ranges are non-binding, ex-GST estimates and may change with material markets and specifications.'},{title:'Production approval',body:'Manufacturing begins only after final artwork, specification, commercial terms and payment milestones are approved.'},{title:'Delivery',body:'Freight timing is estimated and may vary with destination, carrier conditions and events outside production control.'}]}
};
export async function generateMetadata({params}:{params:Promise<{page:string}>}):Promise<Metadata>{const{page}=await params;const data=pages[page];return data?{title:`${data.title} — Paper & Press`,description:data.intro}:{}}
export default async function InfoPage({params}:{params:Promise<{page:string}>}){const{page}=await params;const data=pages[page];if(!data)notFound();return <main className="info-page"><div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>{data.title}</span></div><section className="info-hero"><span>{data.kicker}</span><h1>{data.title}</h1><p>{data.intro}</p></section><section className="info-sections">{data.sections.map((item,index)=><article key={item.title}><span>0{index+1}</span><h2>{item.title}</h2><p>{item.body}</p></article>)}</section><section className="catalog-cta"><p>Ready with a requirement?</p><h2>Let’s price the<br/>production run.</h2><Link href="/quote">Request wholesale quote →</Link></section></main>}
