export type B2BCategory = {
  slug:string; name:string; family:string; summary:string; moq:string; price:string;
  sizes:string[]; grades:string[]; uses:string[]; branded:boolean;
};

export const b2bCategories:B2BCategory[] = [
  {slug:'cake-boxes',name:'Cake Boxes',family:'Bakery & Confectionery',summary:'Strong, food-safe cake carriers with optional windows, handles and custom printing.',moq:'MOQ 500 pcs',price:'₹12–₹48 / pc',sizes:['0.5 kg','1 kg','2 kg','3–5 kg'],grades:['Economy SBS','Premium virgin board','Rigid celebration box'],uses:['Bakeries','Cloud kitchens','Hotels'],branded:true},
  {slug:'pastry-boxes',name:'Pastry Boxes',family:'Bakery & Confectionery',summary:'Compact folding cartons for pastries, macarons, donuts and plated desserts.',moq:'MOQ 1,000 pcs',price:'₹4–₹18 / pc',sizes:['4×4×3 in','6×6×3 in','8×5×3 in','Custom'],grades:['Economy duplex','Food-grade ivory','Premium textured'],uses:['Patisseries','Cafés','Dessert brands'],branded:true},
  {slug:'cupcake-boxes',name:'Cupcake Boxes',family:'Bakery & Confectionery',summary:'Windowed boxes with secure inserts for one, four, six or twelve cupcakes.',moq:'MOQ 1,000 pcs',price:'₹6–₹24 / pc',sizes:['1 cavity','4 cavity','6 cavity','12 cavity'],grades:['Standard board','Windowed premium','Rigid gifting'],uses:['Home bakers','Chains','Events'],branded:true},
  {slug:'mithai-boxes',name:'Mithai & Sweet Boxes',family:'Bakery & Confectionery',summary:'Food-safe sweet boxes with trays, partitions, sleeves and festive finishes.',moq:'MOQ 500 pcs',price:'₹9–₹85 / pc',sizes:['250 g','500 g','1 kg','2 kg'],grades:['Economy folding','Premium laminated','Rigid luxury'],uses:['Mithai brands','Wedding gifting','Hotels'],branded:true},
  {slug:'chocolate-boxes',name:'Chocolate Boxes',family:'Bakery & Confectionery',summary:'Presentation boxes with fitted cavities, ribbons, sleeves and foil detailing.',moq:'MOQ 500 pcs',price:'₹18–₹120 / pc',sizes:['4 cavity','9 cavity','16 cavity','24 cavity'],grades:['Folding carton','Premium drawer','Rigid magnetic'],uses:['Chocolatiers','Luxury gifting','Corporate hampers'],branded:true},
  {slug:'pizza-boxes',name:'Pizza Boxes',family:'QSR & Takeaway',summary:'Ventilated food-grade corrugated pizza boxes for everyday and premium service.',moq:'MOQ 1,000 pcs',price:'₹8–₹32 / pc',sizes:['7 in','9 in','12 in','14 in'],grades:['Economy kraft','E-flute standard','Premium printed'],uses:['Pizzerias','QSR chains','Cloud kitchens'],branded:true},
  {slug:'burger-boxes',name:'Burger & Sandwich Boxes',family:'QSR & Takeaway',summary:'Grease-resistant clamshell and tuck-top formats for burgers and sandwiches.',moq:'MOQ 2,000 pcs',price:'₹3.5–₹12 / pc',sizes:['Slider','Regular','Gourmet','Double burger'],grades:['Economy board','Food-grade kraft','Premium printed'],uses:['Burger brands','Cafés','Food trucks'],branded:true},
  {slug:'fries-trays',name:'Fries & Snack Trays',family:'QSR & Takeaway',summary:'Open paperboard trays for fries, momos, snacks, chaat and tasting portions.',moq:'MOQ 5,000 pcs',price:'₹1.2–₹5 / pc',sizes:['Small','Medium','Large','Loaded fries'],grades:['Economy kraft','Grease barrier','Premium branded'],uses:['QSR','Stadiums','Events'],branded:true},
  {slug:'meal-boxes',name:'Meal & Takeaway Boxes',family:'QSR & Takeaway',summary:'Leak-resistant folding meal boxes for rice, noodles, thalis and combo meals.',moq:'MOQ 2,000 pcs',price:'₹4–₹18 / pc',sizes:['500 ml','750 ml','1,000 ml','2 compartment'],grades:['PE lined','Aqueous barrier','Premium kraft'],uses:['Restaurants','Catering','Cloud kitchens'],branded:true},
  {slug:'food-paper',name:'Food Paper & Wraps',family:'QSR & Takeaway',summary:'Grease-resistant printed sheets for burgers, bakery products and tray lining.',moq:'MOQ 5,000 sheets',price:'₹0.8–₹3.5 / sheet',sizes:['10×10 in','12×12 in','15×12 in','Custom'],grades:['Economy greaseproof','Premium MG paper','Foil-lined'],uses:['QSR','Bakeries','Delis'],branded:true},
  {slug:'paper-cups',name:'Paper Cups',family:'Cafés & Beverages',summary:'Food-grade hot and cold cups in plain, single-wall, double-wall and printed options.',moq:'MOQ 5,000 pcs',price:'₹0.35–₹5 / pc',sizes:['80 ml','150 ml','250 ml','350 ml'],grades:['Plain economy','Single-wall printed','Double-wall premium'],uses:['Cafés','Offices','Events'],branded:true},
  {slug:'cup-sleeves',name:'Cup Sleeves',family:'Cafés & Beverages',summary:'Insulating corrugated sleeves with kraft, one-color or full-color branding.',moq:'MOQ 5,000 pcs',price:'₹1–₹4 / pc',sizes:['4 oz','8 oz','12 oz','16 oz'],grades:['Plain kraft','Single-color','Full-color premium'],uses:['Coffee chains','Tea brands','Events'],branded:true},
  {slug:'cup-carriers',name:'Cup Carriers & Trays',family:'Cafés & Beverages',summary:'Molded fibre and folding board carriers for two or four takeaway beverages.',moq:'MOQ 2,000 pcs',price:'₹3–₹12 / pc',sizes:['2 cup','4 cup','Tray + food','Custom'],grades:['Molded fibre','Kraft board','Printed premium'],uses:['Cafés','Delivery kitchens','Caterers'],branded:true},
  {slug:'coffee-bags',name:'Coffee Bags',family:'Cafés & Beverages',summary:'Valve-equipped pouches and paper-look packs for roasted beans and ground coffee.',moq:'MOQ 1,000 pcs',price:'₹14–₹45 / pc',sizes:['100 g','250 g','500 g','1 kg'],grades:['Stock + label','Digital printed','Premium foil barrier'],uses:['Roasters','Cafés','Private labels'],branded:true},
  {slug:'corrugated-mailers',name:'Corrugated Mailer Boxes',family:'Courier & Corrugated',summary:'Self-locking E-flute mailers for ecommerce, subscriptions and premium dispatch.',moq:'MOQ 500 pcs',price:'₹12–₹55 / pc',sizes:['6×4×2 in','8×6×3 in','10×8×4 in','Custom'],grades:['Plain economy','1-color kraft','Litho-laminated premium'],uses:['D2C brands','Subscriptions','Gifting'],branded:true},
  {slug:'courier-boxes',name:'Courier Shipping Boxes',family:'Courier & Corrugated',summary:'Reliable RSC cartons for door-to-door courier, storage and distribution.',moq:'MOQ 500 pcs',price:'₹7–₹75 / pc',sizes:['Small parcel','Medium parcel','Large parcel','Custom'],grades:['3 ply economy','5 ply medium','7 ply heavy-duty'],uses:['Ecommerce','Warehouses','Distributors'],branded:true},
  {slug:'industrial-cartons',name:'Industrial Corrugated Cartons',family:'Courier & Corrugated',summary:'High-strength board combinations designed for heavy loads and long transport cycles.',moq:'MOQ 500 pcs',price:'₹25–₹220 / pc',sizes:['Up to 10 kg','10–30 kg','30–45 kg','Export custom'],grades:['5 ply','7 ply','HDPE laminated'],uses:['Manufacturers','Exporters','Auto parts'],branded:true},
  {slug:'plain-corrugated-boxes',name:'Plain Corrugated Boxes',family:'Courier & Corrugated',summary:'Unprinted RSC shipping cartons in practical stock and custom dimensions for economical storage, dispatch and distribution.',moq:'MOQ 500 pcs',price:'₹7–₹70 / pc',sizes:['6×4×4 in','10×8×6 in','14×10×8 in','Custom L×B×H'],grades:['3 ply economy','5 ply standard','7 ply heavy-duty'],uses:['Ecommerce sellers','Warehouses','Manufacturers'],branded:false},
  {slug:'garment-boxes',name:'Garment & Apparel Boxes',family:'Fashion & Retail',summary:'Folding and rigid boxes for shirts, sarees, occasionwear and ecommerce apparel.',moq:'MOQ 500 pcs',price:'₹18–₹110 / pc',sizes:['Shirt','Kurta','Saree','Lehenga'],grades:['Economy duplex','Premium corrugated','Rigid luxury'],uses:['Fashion labels','Boutiques','Export houses'],branded:true},
  {slug:'retail-paper-bags',name:'Retail Paper Bags',family:'Fashion & Retail',summary:'Kraft and art-paper bags with rope, ribbon or twisted handles.',moq:'MOQ 1,000 pcs',price:'₹7–₹38 / pc',sizes:['Small','Medium','Large','Bottle'],grades:['Kraft economy','Art paper laminated','Luxury textured'],uses:['Retail stores','Jewellery','Events'],branded:true},
  {slug:'garment-flyers',name:'Garment Flyers & Inserts',family:'Fashion & Retail',summary:'Branded or non-branded promotional flyers, care cards, lookbooks and order inserts.',moq:'MOQ 2,000 pcs',price:'₹0.8–₹12 / pc',sizes:['A6','A5','DL','Custom fold'],grades:['Economy 100 GSM','Premium 170 GSM','Luxury textured'],uses:['Fashion brands','Marketplaces','Boutiques'],branded:true},
  {slug:'masala-boxes',name:'Masala & Spice Boxes',family:'Grocery & FMCG',summary:'Printed folding cartons for spice pouches, jars, sachets and gift assortments.',moq:'MOQ 2,000 pcs',price:'₹3–₹18 / pc',sizes:['50 g','100 g','200 g','Gift set'],grades:['Economy duplex','Food-grade SBS','Premium foil carton'],uses:['Masala brands','Private labels','Exporters'],branded:true},
  {slug:'ghee-boxes',name:'Ghee & Oil Cartons',family:'Grocery & FMCG',summary:'Protective retail cartons sized for jars, tins and pouches with shelf-ready branding.',moq:'MOQ 2,000 pcs',price:'₹4–₹22 / pc',sizes:['200 ml','500 ml','1 L','Twin pack'],grades:['Economy board','Premium SBS','Metallized finish'],uses:['Dairy brands','Organic labels','FMCG'],branded:true},
  {slug:'tea-dryfruit-boxes',name:'Tea & Dry Fruit Boxes',family:'Grocery & FMCG',summary:'Shelf cartons and rigid gift boxes for tea, dry fruits, dates and festive hampers.',moq:'MOQ 500 pcs',price:'₹12–₹140 / pc',sizes:['100 g','250 g','500 g','Assorted gift set'],grades:['Folding carton','Drawer box','Rigid magnetic'],uses:['Tea brands','Dry fruit labels','Corporate gifts'],branded:true},
  {slug:'medicine-cartons',name:'Pharma & Medicine Cartons',family:'Healthcare & Institutional',summary:'Accurately printed unit cartons and secondary packaging for healthcare products.',moq:'MOQ 5,000 pcs',price:'₹1.5–₹9 / pc',sizes:['Small unit','Bottle carton','Tube carton','Custom'],grades:['Economy duplex','Pharma SBS','Braille/foil premium'],uses:['Pharma brands','Nutraceuticals','Clinics'],branded:true},
  {slug:'hospital-files',name:'Hospital & Patient Files',family:'Healthcare & Institutional',summary:'A4 patient record files, OPD folders and diagnostic report covers with custom fields.',moq:'MOQ 1,000 pcs',price:'₹12–₹30 / pc',sizes:['A4','A3 folded','X-ray','Diagnostic report'],grades:['Economy board','300 GSM laminated','PP premium'],uses:['Hospitals','Clinics','Labs'],branded:true},
  {slug:'office-folders',name:'Office Files & Folders',family:'Healthcare & Institutional',summary:'Presentation folders, document wallets, ring files and branded office filing systems.',moq:'MOQ 1,000 pcs',price:'₹8–₹65 / pc',sizes:['A5','A4','Legal','Custom pocket'],grades:['Economy board','Laminated card','Rigid ring file'],uses:['Corporates','Institutions','Real estate'],branded:true},
  {slug:'cosmetic-cartons',name:'Cosmetic & Skincare Cartons',family:'Beauty & Personal Care',summary:'Premium folding cartons and rigid kits for skincare, fragrance and beauty launches.',moq:'MOQ 1,000 pcs',price:'₹5–₹55 / pc',sizes:['Serum','Cream jar','Bottle','Gift kit'],grades:['SBS printed','Textured premium','Rigid luxury'],uses:['Beauty brands','Salons','Private labels'],branded:true},
  {slug:'soap-boxes',name:'Soap & Personal Care Boxes',family:'Beauty & Personal Care',summary:'Paperboard wraps and cartons for handmade soap, wellness bars and bath products.',moq:'MOQ 2,000 pcs',price:'₹2.5–₹14 / pc',sizes:['Mini bar','75 g','100 g','Gift set'],grades:['Kraft economy','SBS printed','Premium windowed'],uses:['Soap makers','Hotels','Wellness brands'],branded:true},
  {slug:'box-inserts-dividers',name:'Box Inserts & Dividers',family:'Fashion & Retail',summary:'Die-cut paperboard and corrugated inserts engineered to hold products securely, organise sets and improve the unboxing experience.',moq:'MOQ 1,000 pcs',price:'₹3–₹35 / pc',sizes:['Single cavity','Multi cavity','Jar / bottle','Custom fit'],grades:['Corrugated economy','Precision paperboard','Premium wrapped'],uses:['D2C brands','Electronics','Gifting'],branded:true},
  {slug:'packaging-sleeves',name:'Packaging Sleeves & Belly Bands',family:'Fashion & Retail',summary:'Printed paper sleeves that add branding, product information and seasonal flexibility without replacing the primary box.',moq:'MOQ 1,000 pcs',price:'₹2–₹16 / pc',sizes:['Small carton','Medium box','Large box','Custom wrap'],grades:['Kraft economy','Printed SBS','Textured / foil'],uses:['Retail brands','Bakeries','Gift boxes'],branded:true},
  {slug:'stickers-labels',name:'Stickers & Product Labels',family:'Fashion & Retail',summary:'Custom die-cut paper and film labels for sealing, product identification, compliance information and branded finishing.',moq:'MOQ 2,000 pcs',price:'₹0.4–₹6 / pc',sizes:['25 mm','50 mm','75 mm','Custom die-cut'],grades:['Paper economy','Water-resistant film','Foil / textured'],uses:['D2C brands','Food brands','Cosmetics'],branded:true},
];

export const catalogFamilies = [...new Set(b2bCategories.map(item=>item.family))];
export const customerShowcase = ['Baggu','PopUp Grocer','Momofuku','Flamingo Estate','Garmentory','Micos','Edie Parker','For Love & Lemons','Carhartt WIP','Partners Coffee','Sweetgreen','Arc’teryx'];
export const galleryFor = (slug:string) => [1,2,3,4].map(index=>`/catalog/${slug}-${String(index).padStart(2,'0')}.png`);
