import type { Metadata } from 'next';
import Link from 'next/link';
import { b2bCategories, catalogFamilies } from '../catalog';
import HoverCardGallery from '../HoverCardGallery';
import {categoryCardGallery} from '../cardGalleries';
export const metadata:Metadata={title:'Wholesale Packaging Catalog — Paper & Press',description:'Bulk boxes, food packaging, paper cups, courier cartons, retail print, hospital files and more with indicative Indian wholesale price ranges.'};

export default async function ProductsPage({searchParams}:{searchParams:Promise<{family?:string;search?:string}>}){const query=await searchParams;const family=query.family;const search=query.search?.toLowerCase();const shown=b2bCategories.filter(i=>(!family||i.family.toLowerCase().includes(family.toLowerCase()))&&(!search||`${i.name} ${i.family} ${i.summary}`.toLowerCase().includes(search)));return <main className="shop-page">
 <div className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>Wholesale catalog</span></div><section className="shop-intro"><span>B2B orders only</span><h1>{family||'All Packaging Categories'}</h1><p>Indicative Indian wholesale price ranges. Final unit pricing depends on size, board grade, print, finish, quantity and delivery PIN code.</p></section>
 <div className="shop-toolbar"><button>☷ Categories</button><span>{shown.length} categories</span><button>Sort: Industry order ⌄</button></div><div className="shop-layout"><aside className="filter-sidebar"><h2>Product families</h2><nav className="catalog-nav"><Link className={!family?'active':''} href="/products">All categories</Link>{catalogFamilies.map(name=><Link className={family===name?'active':''} href={`/products?family=${encodeURIComponent(name)}`} key={name}>{name}<span>{b2bCategories.filter(i=>i.family===name).length}</span></Link>)}</nav><div className="bulk-note"><b>Wholesale only</b><p>Typical MOQs begin at 500–5,000 pieces depending on construction and print method.</p><Link href="/quote">Ask about your run →</Link></div></aside><section className="category-catalog">{shown.map(item=><Link href={`/categories/${item.slug}`} className="catalog-card" key={item.slug}><div className="catalog-card-media"><HoverCardGallery images={categoryCardGallery(item.slug)} alt={item.name}/><span>{item.branded?'Plain + branded':'Plain stock'}</span></div><small>{item.family}</small><h2>{item.name}</h2><p>{item.summary}</p><div><b>{item.price}</b><span>{item.moq}</span></div></Link>)}</section></div><section className="price-disclaimer"><h2>How wholesale pricing works</h2><div><p><b>1. Dimensions</b><br/>Larger dielines use more board and affect freight.</p><p><b>2. Material grade</b><br/>GSM, ply, flute and food barriers determine strength.</p><p><b>3. Print & finish</b><br/>Plain, flexo, offset, foil and lamination price differently.</p><p><b>4. Production volume</b><br/>Higher repeat runs generally reduce the unit rate.</p></div></section></main>}
